# Generated by Django 6.0.2 on 2026-05-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_savedrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_code', models.CharField(max_length=20)),
                ('credential_number', models.CharField(max_length=20)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('university_code', 'credential_number')},
            },
        ),
    ]
