# Generated by Django 6.0.2 on 2026-05-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_validcredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('abbr', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=300)),
            ],
        ),
    ]
