# Generated by Django 6.0.4 on 2026-05-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_universityinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='university_slug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
