# Generated by Django 6.0.4 on 2026-05-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_university_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
