# Generated by Django 6.0.2 on 2026-05-06 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_profile_id_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('paragraph_1', models.TextField(blank=True)),
                ('paragraph_2', models.TextField(blank=True)),
                ('paragraph_3', models.TextField(blank=True)),
                ('paragraph_4', models.TextField(blank=True)),
                ('paragraph_5', models.TextField(blank=True)),
                ('university', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about', to='main.universityinfo')),
            ],
        ),
    ]
