# Generated by Django 6.0.4 on 2026-05-06 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_universityabout'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone_1', models.CharField(blank=True, max_length=50)),
                ('phone_2', models.CharField(blank=True, max_length=50)),
                ('email_pk', models.EmailField(blank=True, max_length=254)),
                ('email_uni', models.EmailField(blank=True, max_length=254)),
                ('youtube', models.CharField(blank=True, max_length=200)),
                ('telegram', models.CharField(blank=True, max_length=200)),
                ('university', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='main.universityinfo')),
            ],
        ),
    ]
