# Generated by Django 6.0.2 on 2026-05-07 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_universitycontacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('university', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='main.universityinfo')),
            ],
        ),
    ]
