# Generated by Django 6.0.2 on 2026-05-07 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_universitywebsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('ЛИПЕНЬ', 'Липень'), ('СЕРПЕНЬ', 'Серпень'), ('ВЕРЕСЕНЬ', 'Вересень'), ('ЖОВТЕНЬ', 'Жовтень'), ('ВЕРЕСЕНЬ | ЖОВТЕНЬ', 'Вересень–Жовтень')], max_length=30)),
                ('event_date', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.universityinfo')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
