# Generated by Django 6.0.2 on 2026-05-07 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_universityevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('july', models.TextField(blank=True)),
                ('august', models.TextField(blank=True)),
                ('sep_oct', models.TextField(blank=True)),
                ('university', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='main.universityinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='UniversityEvent',
        ),
    ]
