# Generated by Django 6.0.2 on 2026-05-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_universitydates_delete_universityevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitydates',
            name='august',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='universitydates',
            name='july',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='universitydates',
            name='sep_oct',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
