# Generated by Django 6.0.2 on 2026-05-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_validcredential_created_by_validcredential_used_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityinfo',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
