# Generated by Django 6.0.2 on 2026-05-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_universityinfo_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityinfo',
            name='has_programs',
            field=models.BooleanField(default=False),
        ),
    ]
