# Generated by Django 6.0.2 on 2026-05-25 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_universityinfo_has_programs'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва освітньої програми')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_programs', to='main.specialty')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_programs', to='main.universityinfo')),
            ],
        ),
    ]
